-- Fix UNIQUE constraint: global orderNumber/invoiceNumber → per-user (userId + invoiceNumber)
-- Reason: DKB Sparplan executions share the same Auftragsnummer across multiple ETFs,
-- and a global unique on invoiceNumber blocks re-imports when orphaned records exist.
-- The startup migration in index.prod.ts handles the actual ALTER TABLE statements.
